# Generated by Django 3.2.9 on 2021-11-26 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211126_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='species',
        ),
    ]
